#!/bin/sh

##
## recover 
##

BIND9_DEV_DIR=/home/db/bind-9.9.3-P2-dubin
SOURCE_DIR=./storage
#############################

#########
# pacth 
#
echo ""
echo ""
echo "patch netmap code ...."
rm -rf ${BIND9_DEV_DIR}/netmap
mkdir -p ${BIND9_DEV_DIR}/netmap

cp -vf ${SOURCE_DIR}/bin/named/{query.c,interfacemgr.c,client.c,Makefile.in} ${BIND9_DEV_DIR}/bin/named/
cp -vf ${SOURCE_DIR}/bin/named/include/named/query.h ${BIND9_DEV_DIR}/bin/named/include/named/
cp -vf ${SOURCE_DIR}/lib/dns/include/dns/dispatch.h ${BIND9_DEV_DIR}/lib/dns/include/dns/ 
cp -vf ${SOURCE_DIR}/lib/dns/dispatch.c ${BIND9_DEV_DIR}/lib/dns/ 
cp -vf ${SOURCE_DIR}/lib/isc/include/isc/{bind9.h,namespace.h,socket.h} ${BIND9_DEV_DIR}/lib/isc/include/isc/ 
cp -vf ${SOURCE_DIR}/lib/isc/unix/{Makefile.in,socket.c} ${BIND9_DEV_DIR}/lib/isc/unix/ 
cp -vf ${SOURCE_DIR}/lib/isc/{socket_api.c,Makefile.in} ${BIND9_DEV_DIR}/lib/isc/ 
cp -vrf ${SOURCE_DIR}/netmap/* ${BIND9_DEV_DIR}/netmap/
cp -vf ${SOURCE_DIR}/Makefile.in ${BIND9_DEV_DIR}/
echo "patch done."
