#!/bin/sh

##
## recover 
##

BIND9_DEV_DIR=/home/db/bind-9.9.3-P2-dubin
BIND9_BACKUP_DIR=./bind9_origin
SOURCE_DIR=./storage
#############################


######
##  backup origin bind9 code
echo ""
echo ""
echo "backup origin code ...."
rm -rf ${BIND9_BACKUP_DIR}
mkdir -p ${BIND9_BACKUP_DIR}

mkdir -p ${BIND9_BACKUP_DIR}/bin/named/
mkdir -p ${BIND9_BACKUP_DIR}/lib/dns/include/dns/
mkdir -p ${BIND9_BACKUP_DIR}/lib/isc/include/isc/
mkdir -p ${BIND9_BACKUP_DIR}/lib/isc/unix/
mkdir -p ${BIND9_BACKUP_DIR}/netmap/net

cp -v ${BIND9_DEV_DIR}/bin/named/client.c ${BIND9_BACKUP_DIR}/bin/named/
cp -v ${BIND9_DEV_DIR}/bin/named/interfacemgr.c ${BIND9_BACKUP_DIR}/bin/named/
cp -v ${BIND9_DEV_DIR}/lib/dns/include/dns/dispatch.h ${BIND9_BACKUP_DIR}/lib/dns/include/dns/
cp -v ${BIND9_DEV_DIR}/lib/dns/dispatch.c ${BIND9_BACKUP_DIR}/lib/dns/
cp -v ${BIND9_DEV_DIR}/lib/isc/include/isc/{bind9.h,namespace.h,socket.h} ${BIND9_BACKUP_DIR}/lib/isc/include/isc/
cp -v ${BIND9_DEV_DIR}/lib/isc/unix/{Makefile.in,socket.c} ${BIND9_BACKUP_DIR}/lib/isc/unix/
cp -v ${BIND9_DEV_DIR}/lib/isc/{Makefile.in,socket_api.c,task.c} ${BIND9_BACKUP_DIR}/lib/isc/
cp -vr ${BIND9_DEV_DIR}/netmap/net/* ${BIND9_BACKUP_DIR}/netmap/net/ 
cp -v ${BIND9_DEV_DIR}/netmap/{Makefile,*.h,*.c} ${BIND9_BACKUP_DIR}/netmap/
cp -v ${BIND9_DEV_DIR}/Makefile.in ${BIND9_BACKUP_DIR}
echo " backup done."

#########
# pacth 
#
echo ""
echo ""
echo "patch netmap code ...."
rm -rf ${BIND9_DEV_DIR}/netmap
mkdir -p ${BIND9_DEV_DIR}/netmap/net

cp -vf ${SOURCE_DIR}/bin/named/{interfacemgr.c,client.c} ${BIND9_DEV_DIR}/bin/named/
cp -vf ${SOURCE_DIR}/lib/dns/include/dns/dispatch.h ${BIND9_DEV_DIR}/lib/dns/include/dns/ 
cp -vf ${SOURCE_DIR}/lib/dns/dispatch.c ${BIND9_DEV_DIR}/lib/dns/ 
cp -vf ${SOURCE_DIR}/lib/isc/include/isc/{bind9.h,namespace.h,socket.h} ${BIND9_DEV_DIR}/lib/isc/include/isc/ 
cp -vf ${SOURCE_DIR}/lib/isc/unix/{Makefile.in,socket.c} ${BIND9_DEV_DIR}/lib/isc/unix/ 
cp -vf ${SOURCE_DIR}/lib/isc/{socket_api.c,task.c,Makefile.in} ${BIND9_DEV_DIR}/lib/isc/ 
cp -vf ${SOURCE_DIR}/netmap/net/* ${BIND9_DEV_DIR}/netmap/net/
cp -vf ${SOURCE_DIR}/netmap/{Makefile,*.h,*.c} ${BIND9_DEV_DIR}/netmap/ 
cp -vf ${SOURCE_DIR}/Makefile.in ${BIND9_DEV_DIR}/
echo "patch done."
